module.exports = function (opts) {
  if (opts.version) {
    var pkg = require('../package.json')
    console.error(pkg.version)
    process.exit(1)
  }
  console.error('Usage: dat <cmd> [options]')
  console.error('   dat create                        create a local archive')
  console.error('   dat snapshot                      create a local snapshot archive')
  console.error('   dat clone <dat-link> <directory>  clone a remote archive')
  console.error('')
  console.error('   dat sync                          sync files with the network')
  console.error('   dat pull                          update from remote archive & exit')
  console.error('')
  console.error('     --dir=<folder>                  set directory')
  console.error('     --no-import                     do not import files (create, sync)')
  console.error('     --quiet                         only print out the dat link')
  console.error('     --port=3282                     set the port for discovery')
  console.error('     --no-utp                        do not use utp for network connections')
  console.error('')
  console.error('   dat register                      register for an account')
  console.error('   dat login                         login to an account')
  console.error('   dat logout                        logout from the server')
  console.error('   dat whoami                        get login information')
  console.error('   dat publish                       publish dataset to registry')
  console.error('')
  console.error('   dat --version, -v                 get your dat version')
  console.error('   dat help                          print this usage guide')
  console.error('   dat doctor                        run the dat network doctor')
  console.error('')
  process.exit(1)
}
